config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :menus do
    resources :foods 

  end

  root 'welcome#index'
  get 'contact_us' => 'contact_us#index'

  get 'foods' => 'foods#show'

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :menu
  has_many :orders

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :foods
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
    render template: "contact_us/contact_us"
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    if params[:menu_id] && params[:id]
      @menu = Menu.find(params[:menu_id])
      @food = @menu.foods.find(params[:id])
    else
      @food = Food.find_all
    end
  end

  def show
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
    @current_menu = params[:query] || 1
    @search = params[:search] || 'menu'

    order = params[:sort] || 'name ASC'
    if(@search != 'search')
      @food = Menu.find(@current_menu).foods.order(order)
    else
      keyword = params[:search_string]
      @food = Food.where('name like ?', "%#{keyword}").order(order)
    end

  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    food_id = params[:food]
    if food_id
      @food = Food.find food_id
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Thank you. Your order has been placed successfully.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :phone, :ship_cost, :total_cost, :discount, :food_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact_us/contact_us.html.erb
<div class="container">
  <div class="row contact">
    <div class="col-sm-6 text-center">
      <h2> The Vietnamese Restaurant</h2>
      36 Ho Tung Mau Street, Ben Nghe ward, District 1, Ho Chi Minh City
    </div>
    <div class="col-sm-6">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.5151495394884!2d106.70225191480066!3d10.771800692324657!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f41476fee6b%3A0x15de2e5129cc54f!2zQml0ZXhjbyBGaW5hbmNpYWwgVG93ZXIsIDIgSOG6o2kgVHJp4buBdSwgQuG6v24gTmdow6ksIFF14bqtbiAxLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1449375119503" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div

app/views/foods/_food.html.erb
<div class="card">
  <img class="card-img-top" src="<%= food.img %>">
  <div class="card-block">
    <h4 class="card-title"><%= food.name %></h4>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= food.description %></li>
      <li class="list-group-item">
        <span class="label label-default pull-right"><%= food.price %> VND</span>
        Price:
      </li>
    </ul>
    <div class="card-footer text-center">
      <%= link_to 'Order', {controller: "orders", action: "new", food: food.id, food_name:food.name, price:food.price }, class:"btn btn-primary" if options[:order] %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-light bg-faded">
  <%=link_to 'Home', root_path %>
  <%=link_to 'Orders', {controller: 'orders', action: 'index'}, class: 'pull-right' %>
</nav>


<div class="container-fluid content">
  <%= yield %>
</div>
</body>
</html>

app/views/menus/_food_list.html.erb
Sort by:
<div class="btn-group" role="group">
  <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Name
  </button>
  <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    <%=link_to 'A-Z order', {controller: 'menus', action: 'index', query: @current_menu, sort: 'name ASC'}, class: 'dropdown-item'%>
    <%=link_to 'Z-A order', {controller: 'menus', action: 'index', query: @current_menu, sort: 'name DESC'}, class: 'dropdown-item'%>
  </div>
</div>
<div class="btn-group" role="group">
  <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Price
  </button>
  <div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
    <%=link_to 'Lowest first', {controller: 'menus', action: 'index', query: @current_menu, sort: 'price ASC'}, class: 'dropdown-item'%>
    <%=link_to 'Highest first', {controller: 'menus', action: 'index', query: @current_menu, sort: 'price DESC'}, class: 'dropdown-item'%>
  </div>
</div>
</div>
<div class="menu-content">
<% @food.each do |food| %>
<div class="col-sm-5">
  <%= render food, options: {order: true}%>
</div>
<% end %>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<li class="nav-item">
  <%=link_to menu.name, {controller: 'menus', action: 'index', query: menu.id}, class: 'btn btn-primary btn-block'%>
</li>

app/views/menus/_search.html.erb
<%= form_tag '/menus', method: :get, class: "form-inline" do %>
  <%= text_field_tag :search_string,"",class: "form-control", placeholder: "Search" %>
  <%= hidden_field_tag :search, 'search' %>
  <%= submit_tag("Search", class: "btn btn-success-outline")%>
<% end %>

<div class="menu-content">
<% @food.each do |food| %>
<div class="col-sm-5">
  <%= render food, options: {order: true}%>
</div>
<% end %>
</div>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h2>Today menu</h2>

<div class="container col-sm-2 pull-left">
  <div class="nav nav-pills nav-stacked">
    <%= render @menus %>
    <div class="break-line">
        <%=link_to 'Search', {controller: 'menus', action: 'index', search: 'search'}, class: 'btn btn-secondary btn-block'%>
  </div>
  </div>
</div>
<div class="col-sm-10 menu-content pull-right">
  <div class="content">
    <% if @search != 'search' %>
      <%=render 'food_list'%>
    <% else %>
      <%=render 'search'%>
    <% end %>
  </div>
</div>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Please fill your name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Please fill your address" %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label "Please fill your phone number" %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label "The delivery cost would be 20000 VND" %><br>
    <%= f.hidden_field :ship_cost, :value => 20000%>
  </div>
  <div class="field">
    <%= f.label "Total: " + (params[:price].to_i + 20000).to_s + 'VND'%><br>
    <%= f.hidden_field :total_cost, :value => (params[:price].to_i + 20000) %>
  </div>
  <%= f.hidden_field :discount, :value => 0%>
  <%= f.hidden_field :food_id, :value => params[:food]%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Your Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Ship cost</th>
      <th>Total cost</th>
      <th>Discount</th>
      <th>Food</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.phone %></td>
        <td><%= order.ship_cost %></td>
        <td><%= order.total_cost %></td>
        <td><%= order.discount %></td>
        <td><%= order.food.name %></td>
        <td><%= order.created_at.strftime("%FT%T") %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p id="notice"><%= notice %></p>

app/views/orders/new.html.erb
<div class="container">
  <h1>You have chosen <%=params[:food_name].to_s%></h1>
  <div class="col-sm-4">
    <%= render @food, options: {order: false}%>
  </div>
  <div class="col-sm-8">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="order-detail">
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Ship cost:</strong>
  <%= @order.ship_cost %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @order.total_cost %>
</p>

<p>
  <strong>Food:</strong>
  <%= Food.find(@order.food_id).name %>
</p>

<p id="notice"><%= notice %></p>
</div>

app/views/welcome/index.html.erb
<div class ="welcome img-responsive">
  <h1> The Vietnamese Restaurant </h1>
  <%= link_to 'Menu', {controller: 'menus', action: 'index'}, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'Contact us', {controller: 'contact_us'}, class: 'btn btn-primary btn-lg' %>
</row>